import io

open( "1_ Book 1 - Chapter 01 - A Long-expected Party.mp3", "w" )
open( "1_ Book 1 - Chapter 02 - The Shadow of the Past.mp3", "w" )
open( "1_ Book 1 - Chapter 03 - Three is Company.mp3", "w" )
open( "1_ Book 1 - Chapter 04 - A Short Cut to Mushrooms.mp3", "w" )
open( "1_ Book 1 - Chapter 05 - A Conspiracy Unmasked.mp3", "w" )
open( "1_ Book 1 - Chapter 06 - The Old Forest.mp3", "w" )
open( "1_ Book 1 - Chapter 07 - In the House of Tom Bombadil.mp3", "w" )
open( "1_ Book 1 - Chapter 08 - Fog on the Barrow-downs.mp3", "w" )
open( "1_ Book 1 - Chapter 09 - At the Sign of the Prancing Pony.mp3", "w" )
open( "1_ Book 1 - Chapter 10 - Strider.mp3", "w" )
open( "1_ Book 1 - Chapter 11 - A Knife in the Dark.mp3", "w" )
open( "1_ Book 1 - Chapter 12 - Flight to the Ford.mp3", "w" ) 

open( "2_ Book 2 - Chapter 01 - Many Meetings.mp3", "w" )
open( "2_ Book 2 - Chapter 02 - The Council of Elrond.mp3", "w" )
open( "2_ Book 2 - Chapter 03 - The Ring goes South.mp3", "w" )
open( "2_ Book 2 - Chapter 04 - A Journey in the Dark.mp3", "w" )
open( "2_ Book 2 - Chapter 05 - The Bridge of Khazad-dum.mp3", "w" )
open( "2_ Book 2 - Chapter 06 - Lothlorien.mp3", "w" )
open( "2_ Book 2 - Chapter 07 - The Mirror of Galadriel.mp3", "w" )
open( "2_ Book 2 - Chapter 08 - Farewell to Lorien.mp3", "w" )
open( "2_ Book 2 - Chapter 09 - The Great River.mp3", "w" )
open( "2_ Book 2 - Chapter 10 - The Breaking of the Fellowship.mp3", "w" )

open( "3_ Book 3 - Chapter 01 - The Departure of Boromir.mp3", "w" )
open( "3_ Book 3 - Chapter 02 - The Riders of Rohan.mp3", "w" )
open( "3_ Book 3 - Chapter 03 - The Uruk-hai.mp3", "w" )
open( "3_ Book 3 - Chapter 04 - Treebeard.mp3", "w" )
open( "3_ Book 3 - Chapter 05 - The White Rider.mp3", "w" )
open( "3_ Book 3 - Chapter 06 - The King of the Golden Hall.mp3", "w" )
open( "3_ Book 3 - Chapter 07 - Helm's Deep.mp3", "w" )
open( "3_ Book 3 - Chapter 08 - The Road to Isengard.mp3", "w" )
open( "3_ Book 3 - Chapter 09 - Flotsam and Jetsam.mp3", "w" )
open( "3_ Book 3 - Chapter 10 - The Voice of Saruman.mp3", "w" )
open( "3_ Book 3 - Chapter 11 - The Palantir.mp3", "w" )
 
open( "4_ Book 4 - Chapter 01 - The Taming of Smeagol.mp3", "w" )
open( "4_ Book 4 - Chapter 02 - The Passage of the Marshes.mp3", "w" )
open( "4_ Book 4 - Chapter 03 - The Black Gate is Closed.mp3", "w" )
open( "4_ Book 4 - Chapter 04 - Of Herbs and Stewed Rabbit.mp3", "w" )
open( "4_ Book 4 - Chapter 05 - The Window on the West.mp3", "w" )
open( "4_ Book 4 - Chapter 06 - The Forbidden Pool.mp3", "w" )
open( "4_ Book 4 - Chapter 07 - Journey to the Cross-roads.mp3", "w" )
open( "4_ Book 4 - Chapter 08 - The Stairs of Cirith Ungol.mp3", "w" )
open( "4_ Book 4 - Chapter 09 - Shelob's Lair.mp3", "w" )
open( "4_ Book 4 - Chapter 10 - The Choices of Master Samwise.mp3", "w" )

open( "1_ Book 5 - Chapter 01 - Minas Tirith.mp3", "w" )
open( "1_ Book 5 - Chapter 02 - The Passing of the Grey Company.mp3", "w" )
open( "1_ Book 5 - Chapter 03 - The Muster of Rohan.mp3", "w" )
open( "1_ Book 5 - Chapter 04 - The Siege of Gondor.mp3", "w" )
open( "1_ Book 5 - Chapter 05 - The Ride of the Rohirrim.mp3", "w" )
open( "1_ Book 5 - Chapter 06 - The Battle of the Pelennor Fields.mp3", "w" )
open( "1_ Book 5 - Chapter 07 - The Pyre of Denethor.mp3", "w" )
open( "1_ Book 5 - Chapter 08 - The Houses of Healing.mp3", "w" )
open( "1_ Book 5 - Chapter 09 - The Last Debate.mp3", "w" )
open( "1_ Book 5 - Chapter 10 - The Black Gate Opens.mp3", "w" )

open( "2_ Book 6 - Chapter 01 - The Tower of Cirith Ungol.mp3", "w" )
open( "2_ Book 6 - Chapter 02 - The Land of Shadow.mp3", "w" )
open( "2_ Book 6 - Chapter 03 - Mount Doom.mp3", "w" )
open( "2_ Book 6 - Chapter 04 - The Field of Cormallen.mp3", "w" )
open( "2_ Book 6 - Chapter 05 - The Steward and the King.mp3", "w" )
open( "2_ Book 6 - Chapter 06 - Many Partings.mp3", "w" )
open( "2_ Book 6 - Chapter 07 - Homeward Bound.mp3", "w" )
open( "2_ Book 6 - Chapter 08 - The Scouring of the Shire.mp3", "w" )
open( "2_ Book 6 - Chapter 09 - The Grey Havens.mp3", "w" )
